# Template configuration

# Format template command: command name required parameters [optional parameters] <destination account
#    For example: Rice 20 <zfb
#    1. There can be multiple command names, all of which can trigger the same template;
#    2. The target account can be omitted. Omit will use the default account
#    3. Use spaces to separate the parameters, you can use quotation marks (") to wrap the parameters with spaces

config:
  # Target account
  accounts:
    zfb: 'Assets:Digital:Alipay'
    wx: 'Assets:Digital:Wechat'
  # Default Account
  default_account:
    'Assets:Digital:Alipay'

templates:
  # Template definition
  # command: Set the command name. Can be a value or an array
  # args: template parameters. Required when using it, you can use {parameter} to quote when defining the template
  # optional_args: optional parameters. No, it will follow the template parameter when used, the default is an empty string
  # computed: The parameters that need to be calculated. It can be followed by a Python expression statement, and the passed-in parameters and built-in variables can be used in the statement
  # template: Define the final generated transaction statement. You can use {variable} to reference:
  #    1. Built-in variables: account (account), date (date), command (command entered by the user, which may be different for multiple commands)
  #    2. Various parameters: parameters, optional parameters, and calculation parameters can all be quoted

  - command: 'vultr'
    template: |
      {date} * "Vultr" "Monthly fee"
        {account}
        Expenses:Tech:Cloud    5 USD
  - command : [ 'drink', 'drink', 'coffee']
    args:
      - 'price'
    template: |
      {date} * "" "{command}"
        {account}
        Expenses:Food:Drink    {price} CNY
  - command : 'rice'
    args:
      - 'price'
    optional_args:
      - 'restaurant'
    computed:
      hour: __import__('datetime').datetime.now().hour
      expense: |
        'Expenses:Food:Extra' if hour <= 3 or hour >= 21 else \
        'Expenses:Food:Dinner:Breakfast' if hour <= 10 else \
        'Expenses:Food:Dinner:Lunch' if hour <= 16 else \
        'Expenses:Food:Dinner:Supper'
    template: |
      {date} * "{restaurant}" "meal"
        {account}
        {expense}  {price} CNY